"""``Reading List.md``: the pending screening rows, rendered.

The ledger is the source of truth and this note is a view of it. Nothing here
parses Markdown back into a decision, so the file can be deleted at any time and
rebuilt from ``screening.tsv`` — which is exactly what every command that
changes the ledger does as its last step.

It is a **sibling** of the papers folder, not a note in it. ``papers_dir.glob``
is walked by `bib`, `find`, the root scan and `--report`'s note count; a
generated file living among the notes would need an exclusion rule in every one
of those, and a forgotten guard would silently corrupt a bibliography or a
PRISMA number.
"""

from __future__ import annotations

import datetime as dt
from dataclasses import dataclass
from typing import TYPE_CHECKING, Final

import yaml

from research_assistant import screening, search

if TYPE_CHECKING:
    from collections.abc import Mapping, Sequence
    from pathlib import Path

READING_LIST_FILENAME: Final = "Reading List.md"

_GENERATED: Final = (
    "*Generated by the `reading-list` command from the pending rows of "
    "`screening.tsv` "
    "— do not hand-edit; anything written here is overwritten.*"
)

_MULTI_HEADING: Final = "Reached from several of your papers"
_UNATTRIBUTED_HEADING: Final = "Unattributed"
_COLUMNS: Final[tuple[str, ...]] = (
    "Year",
    "Title",
    "Authors",
    "Venue",
    "Cites",
    "Via",
    "Id",
)
_EMPTY: Final = "Nothing is pending. Run `expand` to find candidates."


def path_for(papers_dir: Path) -> Path:
    """A sibling of ``pdfs/``, ``topics/`` and ``screening.tsv``."""
    return papers_dir.parent / READING_LIST_FILENAME


@dataclass(frozen=True, slots=True)
class Selector:
    """What subset of the pending set a command is talking about.

    ``min_year`` and ``min_citations`` read as a floor when `expand` harvests
    and as a filter when a command narrows the pending set. The same predicate
    serves both, which is what makes the dual reading coherent.
    """

    query: str = ""
    seeds: tuple[str, ...] = ()
    via: tuple[str, ...] = ()
    min_year: int | None = None
    min_citations: int | None = None

    @property
    def empty(self) -> bool:
        """Whether it selects the whole pending set."""
        return not (
            self.query.strip()
            or self.seeds
            or self.via
            or self.min_year is not None
            or self.min_citations is not None
        )


def matches(row: screening.Decision, selector: Selector) -> bool:
    """Whether one pending row is in ``selector``'s set. Pure."""
    if selector.seeds and not set(row.seeds) & set(selector.seeds):
        return False
    if selector.via and not set(row.via) & set(selector.via):
        return False
    # An unknown year or citation count fails a floor rather than passing it,
    # the same way `_select` treats a work OpenAlex gives no year for.
    if selector.min_year is not None and (
        row.year is None or row.year < selector.min_year
    ):
        return False
    if selector.min_citations is not None and (
        row.citations is None or row.citations < selector.min_citations
    ):
        return False
    title = row.title.lower()
    return all(word in title for word in selector.query.lower().split())


def order(rows: Sequence[screening.Decision]) -> list[screening.Decision]:
    """Rank by how many of your papers reached it, then fame, then recency."""
    return sorted(
        rows,
        key=lambda r: (-len(r.seeds), -(r.citations or 0), -(r.year or 0), r.title),
    )


def select(
    rows: Sequence[screening.Decision],
    selector: Selector,
    *,
    limit: int | None = None,
) -> tuple[screening.Decision, ...]:
    """The ranked subset ``selector`` names."""
    kept = order([row for row in rows if matches(row, selector)])
    return tuple(kept[:limit] if limit is not None else kept)


def _cell(text: str) -> str:
    """A pipe in a title would end the column early and shear the table."""
    return " ".join(text.split()).replace("|", r"\|")


def _link(row: screening.Decision) -> str:
    if row.doi:
        return f"https://doi.org/{row.doi}"
    return f"https://openalex.org/{row.openalex_id}" if row.openalex_id else ""


def _row(row: screening.Decision) -> str:
    title = _cell(row.title or "Untitled")
    url = _link(row)
    cells = (
        str(row.year) if row.year is not None else "",
        f"[{title}]({url})" if url else title,
        _cell(search.byline(row.authors)) if row.authors else "",
        _cell(row.venue),
        str(row.citations) if row.citations is not None else "",
        ", ".join(row.via),
        f"`{row.openalex_id}`" if row.openalex_id else f"`{row.doi or ''}`",
    )
    return "| " + " | ".join(cells) + " |"


def _table(rows: Sequence[screening.Decision]) -> str:
    head = "| " + " | ".join(_COLUMNS) + " |"
    rule = "|" + "---|" * len(_COLUMNS)
    return "\n".join([head, rule, *(_row(row) for row in rows)])


def _heading_for(seed: str, notes: Mapping[str, str]) -> str:
    """The section title for a single-seed group, named for the seed's note."""
    name = notes.get(seed)
    if name is None:
        return f"From {seed} (no note in the vault)"
    return f"From [[{name}]]"


def _sections(
    rows: Sequence[screening.Decision], notes: Mapping[str, str]
) -> list[tuple[str, list[screening.Decision]]]:
    """Group the pending set, each candidate appearing in exactly one group.

    A candidate several of your own papers reached is the strongest signal in
    the list, so it leads and is never repeated under any single seed.
    """
    multi = [row for row in rows if len(row.seeds) >= 2]
    unattributed = [row for row in rows if not row.seeds]
    by_seed: dict[str, list[screening.Decision]] = {}
    for row in rows:
        if len(row.seeds) == 1:
            by_seed.setdefault(row.seeds[0], []).append(row)

    sections: list[tuple[str, list[screening.Decision]]] = []
    if multi:
        sections.append((_MULTI_HEADING, order(multi)))
    sections.extend(
        (_heading_for(seed, notes), order(group))
        for seed, group in sorted(
            by_seed.items(), key=lambda item: (-len(item[1]), item[0])
        )
    )
    if unattributed:
        sections.append((_UNATTRIBUTED_HEADING, order(unattributed)))
    return sections


def render(
    rows: Sequence[screening.Decision],
    *,
    notes: Mapping[str, str],
    updated: str | None = None,
) -> str:
    """The whole note, wholesale. Pure given ``updated``.

    ``updated`` is a date rather than a timestamp so that re-rendering an
    unchanged ledger produces an unchanged file.
    """
    front = yaml.safe_dump(
        {
            "title": "Reading List",
            "pending": len(rows),
            "updated": updated or dt.date.today().isoformat(),
            "tags": ["reading-list"],
        },
        sort_keys=False,
        allow_unicode=True,
        width=10_000,
    )
    # An empty list still renders: a stale note left behind by an earlier run
    # would otherwise claim candidates that have all been decided.
    body = "\n\n".join(
        f"## {heading} ({len(group)})\n\n{_table(group)}"
        for heading, group in _sections(rows, notes)
    )
    return f"---\n{front}---\n\n{_GENERATED}\n\n{body or _EMPTY}\n"


def write(
    papers_dir: Path,
    rows: Sequence[screening.Decision],
    *,
    notes: Mapping[str, str],
) -> Path:
    """Regenerate the note from ``rows``. Returns where it was written."""
    path = path_for(papers_dir)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(rows, notes=notes), encoding="utf-8")
    return path
