"""Obsidian vault backend for the “Research Resources” database.

One Markdown note per resource, named ``<cite_key>.md``, with the bibliographic
record in YAML frontmatter. The filename is the uniqueness guard.

The frontmatter holds only *intrinsic* properties — facts about the resource
itself. Judgements about it (is it any good, does it belong in related work) and
progress through it (read yet?) are prose in the note body, not properties: a
five-point scale in a table is a worse record of an opinion than a sentence is.
The ``read`` tag is not a counter-example: nobody sets it, :func:`sync_read_tag`
derives it from whether the body holds a takeaway or quotes, so it is a fact
about the note rather than a claim someone has to keep true by hand.

A note's *body* is written once and never rewritten: Obsidian owns it
afterwards, and its property editor reformats frontmatter freely. Reading
tolerates that; writing does not fight it.

The one exception is :func:`update_frontmatter`, which the citation-graph linker
uses to refresh ``cites``, ``topics`` and ``tags`` — facts about where a paper
sits in the graph, which change as the vault grows and so cannot be write-once.
It rewrites only the keys it is given, preserves the existing key order, and
leaves the body byte-for-byte identical.
"""

from __future__ import annotations

import re
from typing import TYPE_CHECKING, Any

import yaml

from earth_computers.refs.models import Paper

if TYPE_CHECKING:
    from collections.abc import Mapping, Sequence
    from pathlib import Path

# PDFs sit beside the notes, in a sibling of the papers folder. Obsidian
# resolves ``![[<key>.pdf]]`` by filename, so the exact location only has to be
# somewhere in the vault. They keep the cite key as their name: a PDF is never
# read as prose, and the key avoids the punctuation a title drags in.
PDFS_DIRNAME = "pdfs"

# Topic hub notes sit in another sibling of the papers folder. A topic is only
# worth a note once two papers share it: a label appearing on one paper of 157
# groups nothing, and as a graph node it is a hair rather than a cluster.
TOPICS_DIRNAME = "topics"
MIN_TOPIC_PAPERS = 2

_GENERATED = (
    "*Generated by `just relink` from the OpenAlex topics of the papers below "
    "— do not hand-edit; anything written here is overwritten.*"
)

# Obsidian rejects these in file names; # ^ [ ] additionally mean something in
# link syntax and would break a ``[[wikilink]]`` to the note. Slashes become a
# dash rather than vanishing — deleting one turns "TCP/IP" into "TCPIP".
_SEPARATORS = re.compile(r"\s*[\\/]\s*")
_FORBIDDEN = re.compile(r'[:*?"<>|#^\[\]]')

_FENCE = "---"
_PDF_MAGIC = b"%PDF-"

# The note body is a fixed set of sections in a fixed order. ``PDF`` is the only
# one dropped when empty; the other three are prompts, and a missing heading is
# a worse invitation to write than an empty one.
BODY_SECTIONS = ("Key takeaway", "Abstract", "Notes")
PDF_SECTION = "PDF"

# A note counts as read once it holds something no index could have supplied: a
# takeaway written by hand, or quotes recovered from its own highlights.
# ``Abstract`` is deliberately not evidence — ``tidy`` backfills it from
# OpenAlex without anyone having read a word.
READ_SECTIONS = ("Key takeaway", "Notes")
READ_TAG = "read"

_HEADING = re.compile(r"^## (.+?)[ \t]*$", re.MULTILINE)


class VaultError(Exception):
    """Raised when the vault is missing, malformed, or would be clobbered."""


def _split_frontmatter(text: str) -> tuple[dict[str, Any], str]:
    """Split a note into its frontmatter mapping and its body.

    The split is on the *first* closing fence only. A ``---`` horizontal rule
    later in the prose is body, not a delimiter — splitting on it as well would
    silently truncate the note, which matters now that
    :func:`update_frontmatter` reattaches the body it reads here.
    """
    if not text.startswith(_FENCE):
        return {}, text
    rest = text[len(_FENCE) :]
    marker = f"\n{_FENCE}"
    end = rest.find(marker)
    if end == -1:
        return {}, text
    loaded = yaml.safe_load(rest[:end])
    body = rest[end + len(marker) :].lstrip("\n")
    return (loaded if isinstance(loaded, dict) else {}), body


def _int(value: Any) -> int | None:
    return int(value) if isinstance(value, int | float) else None


def _str(value: Any) -> str | None:
    text = str(value).strip() if value is not None else ""
    return text or None


def note_name(title: str, key: str) -> str:
    """What the note is called in the vault: the title, made filename-safe.

    The verbatim title stays in the ``title`` property, which is what BibTeX
    reads, so sanitising here costs nothing bibliographically. A colon becomes
    a dash rather than vanishing, since it usually separates a title from its
    subtitle and reads wrong when simply deleted.
    """
    name = _SEPARATORS.sub("-", title.replace(": ", " - ").replace(":", " - "))
    cleaned = " ".join(_FORBIDDEN.sub("", name).split()).strip(". -")
    # A title made only of punctuation would leave a meaningless file name.
    return cleaned if any(char.isalnum() for char in cleaned) else key


def note_text(
    paper: Paper,
    key: str,
    *,
    pdf_name: str | None = None,
    openalex_id: str | None = None,
    topics: Sequence[str] = (),
    tags: Sequence[str] = ("paper",),
) -> str:
    """Render the full Markdown note for ``paper``.

    The abstract goes in the body, not the frontmatter: Obsidian rewrites
    multi-line properties on edit, and it is 2000 characters of noise in a table.
    ``pdf_name`` embeds the saved PDF; without one the note still records
    ``pdf_url`` so the paper can be fetched by hand later.

    ``openalex_id`` is the join key for the citation graph, and the only way to
    identify the works that have no DOI. Like the DOI it is an intrinsic
    property of the resource, so it belongs in frontmatter.
    """
    front: dict[str, Any] = {
        "title": paper.title,
        "cite_key": key,
        "entry_type": paper.entry_type,
        "authors": list(paper.authors),
        "year": paper.year,
        "venue": paper.venue,
        "doi": paper.doi,
        "openalex_id": openalex_id,
        "url": paper.url,
        "pdf": f"[[{pdf_name}]]" if pdf_name else None,
        "pdf_url": paper.pdf_url,
        "code_url": None,
        "citations": paper.citations,
        "open_access": paper.open_access.lower() if paper.open_access else None,
        "topics": list(topics),
        "cites": [],
        "tags": list(tags),
    }
    dumped = yaml.safe_dump(front, sort_keys=False, allow_unicode=True, width=10_000)
    abstract = paper.abstract or ""
    # The embed goes last: a rendered PDF is tall, and the notes matter more.
    body = render_body(
        {"Abstract": abstract, PDF_SECTION: f"![[{pdf_name}]]" if pdf_name else ""}
    )
    return f"{_FENCE}\n{dumped}{_FENCE}\n\n{body}"


def save_pdf(key: str, data: bytes, *, pdfs_dir: Path) -> Path:
    """Write ``<key>.pdf`` into the vault. Returns the new file path."""
    if not data.startswith(_PDF_MAGIC):
        raise VaultError(
            f"{key}: the download is not a PDF — publishers behind a bot check "
            "serve an HTML block page with a 200. Save it from the browser instead."
        )
    pdfs_dir.mkdir(parents=True, exist_ok=True)
    path = pdfs_dir / f"{key}.pdf"
    path.write_bytes(data)
    return path


def find_by_doi(doi: str, *, papers_dir: Path) -> Path | None:
    """Return the note holding this DOI, if any."""
    if not papers_dir.is_dir():
        return None
    wanted = doi.strip().lower()
    for path in sorted(papers_dir.glob("*.md")):
        front, _ = _split_frontmatter(path.read_text(encoding="utf-8"))
        if _str(front.get("doi")) and str(front["doi"]).strip().lower() == wanted:
            return path
    return None


def create_paper(
    paper: Paper,
    key: str,
    *,
    papers_dir: Path,
    pdf_name: str | None = None,
    openalex_id: str | None = None,
    topics: Sequence[str] = (),
    tags: Sequence[str] = ("paper",),
) -> Path:
    """Write the note into the vault, named for its title. Returns its path."""
    papers_dir.mkdir(parents=True, exist_ok=True)
    path = papers_dir / f"{note_name(paper.title, key)}.md"
    if path.exists():
        raise VaultError(f"{path} already exists — refusing to overwrite it")
    path.write_text(
        note_text(
            paper,
            key,
            pdf_name=pdf_name,
            openalex_id=openalex_id,
            topics=topics,
            tags=tags,
        ),
        encoding="utf-8",
    )
    return path


def parse_body(body: str) -> dict[str, str]:
    """Split a note body into ``{heading: content}``, in document order.

    Headings the template does not know about are kept, so a section the user
    added by hand survives a reformat.
    """
    sections: dict[str, str] = {}
    matches = list(_HEADING.finditer(body))
    for index, match in enumerate(matches):
        end = matches[index + 1].start() if index + 1 < len(matches) else len(body)
        sections[match.group(1)] = body[match.end() : end].strip()
    return sections


def render_body(sections: Mapping[str, str]) -> str:
    """Render the canonical body: one blank line after every heading, always.

    Notes were written by three different code paths over time and drifted into
    five distinct whitespace shapes. The exact spacing does not matter; having
    one of them does, because a diff should show a changed sentence rather than
    a changed blank line.
    """
    known = {*BODY_SECTIONS, PDF_SECTION}
    blocks = [
        f"## {name}\n\n{content}"
        if (content := (sections.get(name) or "").strip())
        else f"## {name}"
        for name in BODY_SECTIONS
    ]
    # Hand-written sections keep their place, after the template's own.
    blocks.extend(
        f"## {name}\n\n{content}"
        for name, raw in sections.items()
        if name not in known and (content := raw.strip())
    )
    if pdf := (sections.get(PDF_SECTION) or "").strip():
        blocks.append(f"## {PDF_SECTION}\n\n{pdf}")
    return "\n\n".join(blocks) + "\n"


def write_body(path: Path, body: str) -> bool:
    """Replace a note's body, leaving its frontmatter byte-for-byte."""
    text = path.read_text(encoding="utf-8")
    front, existing = _split_frontmatter(text)
    if not front or existing == body:
        return False
    head = text[: len(text) - len(existing)]
    path.write_text(head + body, encoding="utf-8")
    return True


def topic_link(topic: str) -> str:
    """The wikilink a paper uses to point at a topic hub note."""
    return f"[[{note_name(topic, topic)}]]"


def write_topic_hub(
    topic: str,
    papers: Sequence[tuple[str, int | None, int | None]],
    *,
    topics_dir: Path,
) -> Path:
    """Write the hub note for ``topic``, listing its papers newest first.

    The listing is what makes the hub a document rather than an empty stub, and
    it is regenerated wholesale, so a topic losing a paper does not leave a
    stale link behind. ``papers`` is ``(note name, year, citations)``.
    """
    topics_dir.mkdir(parents=True, exist_ok=True)
    path = topics_dir / f"{note_name(topic, topic)}.md"
    front = yaml.safe_dump(
        {"title": topic, "papers": len(papers), "tags": ["topic"]},
        sort_keys=False,
        allow_unicode=True,
        width=10_000,
    )
    lines = [
        f"- [[{name}]]{f' ({year})' if year else ''}"
        f"{f' — {citations} citations' if citations else ''}"
        for name, year, citations in sorted(
            papers, key=lambda p: (-(p[1] or 0), p[0].lower())
        )
    ]
    body = "\n".join(lines)
    path.write_text(
        f"{_FENCE}\n{front}{_FENCE}\n\n{_GENERATED}\n\n## Papers\n\n{body}\n",
        encoding="utf-8",
    )
    return path


def is_read(sections: Mapping[str, str]) -> bool:
    """Whether a note body records having actually read the resource."""
    return any((sections.get(name) or "").strip() for name in READ_SECTIONS)


def sync_read_tag(path: Path, sections: Mapping[str, str]) -> bool:
    """Add or drop the ``read`` tag to match the note's own prose.

    The tag is *derived*, never asserted: it is a view of the body, so emptying
    a note's takeaway and quotes retracts it again. That is what keeps it a fact
    about the note rather than a status field somebody has to remember to
    update, and so what lets it live in frontmatter at all.
    """
    tags = [str(tag) for tag in read_frontmatter(path).get("tags") or []]
    if is_read(sections) == (READ_TAG in tags):
        return False
    updated = (
        [*tags, READ_TAG]
        if is_read(sections)
        else [tag for tag in tags if tag != READ_TAG]
    )
    return update_frontmatter(path, {"tags": updated})


def read_frontmatter(path: Path) -> dict[str, Any]:
    """Return just the frontmatter mapping of one note."""
    front, _ = _split_frontmatter(path.read_text(encoding="utf-8"))
    return front


def read_note(path: Path) -> tuple[dict[str, Any], str]:
    """Return ``(frontmatter, body)`` for one note.

    The public form of the split. Readers that need the prose as well as the
    properties — searching it, reformatting it — would otherwise reach for the
    private helper.
    """
    return _split_frontmatter(path.read_text(encoding="utf-8"))


def index(papers_dir: Path) -> tuple[dict[str, Path], dict[str, Path]]:
    """Build ``(by DOI, by OpenAlex id)`` lookups over the whole vault in one pass.

    :func:`find_by_doi` re-reads every note per call, which is fine for adding a
    single paper and quadratic when reconciling hundreds against each other.
    """
    by_doi: dict[str, Path] = {}
    by_openalex: dict[str, Path] = {}
    if not papers_dir.is_dir():
        return by_doi, by_openalex
    for path in sorted(papers_dir.glob("*.md")):
        front = read_frontmatter(path)
        doi = _str(front.get("doi"))
        if doi:
            by_doi.setdefault(doi.lower(), path)
        openalex_id = _str(front.get("openalex_id"))
        if openalex_id:
            by_openalex.setdefault(openalex_id, path)
    return by_doi, by_openalex


def update_frontmatter(path: Path, updates: dict[str, Any]) -> bool:
    """Rewrite only the named frontmatter keys. Returns whether anything changed.

    The body is reattached byte-for-byte and existing key order is preserved, so
    a note the user has since written notes into is not disturbed. Keys absent
    from the note are appended in the order given.
    """
    text = path.read_text(encoding="utf-8")
    front, body = _split_frontmatter(text)
    if not front:
        raise VaultError(f"{path} has no frontmatter to update")
    if all(key in front and front[key] == value for key, value in updates.items()):
        return False

    merged = dict(front)
    merged.update(updates)
    dumped = yaml.safe_dump(merged, sort_keys=False, allow_unicode=True, width=10_000)
    path.write_text(f"{_FENCE}\n{dumped}{_FENCE}\n\n{body}", encoding="utf-8")
    return True


def _note_to_paper(
    front: dict[str, Any], fallback_key: str
) -> tuple[Paper, str] | None:
    title = _str(front.get("title"))
    if not title:
        return None

    raw_authors = front.get("authors")
    authors = (
        tuple(str(a).strip() for a in raw_authors if str(a).strip())
        if isinstance(raw_authors, list)
        else ()
    )

    paper = Paper(
        title=title,
        authors=authors,
        year=_int(front.get("year")),
        doi=_str(front.get("doi")),
        venue=_str(front.get("venue")),
        url=_str(front.get("url")),
        citations=_int(front.get("citations")),
        open_access=_str(front.get("open_access")),
        entry_type=_str(front.get("entry_type")) or "article",
        pdf_url=_str(front.get("pdf_url")),
    )
    return paper, (_str(front.get("cite_key")) or fallback_key)


def read_all(*, papers_dir: Path) -> list[tuple[Paper, str]]:
    """Read every note in the papers folder."""
    if not papers_dir.is_dir():
        raise VaultError(
            f"{papers_dir} does not exist. Set VAULT_PAPERS_DIR, or create the folder."
        )
    entries: list[tuple[Paper, str]] = []
    for path in sorted(papers_dir.glob("*.md")):
        front, _ = _split_frontmatter(path.read_text(encoding="utf-8"))
        entry = _note_to_paper(front, path.stem)
        if entry is not None:
            entries.append(entry)
    return entries
